// // app/dashboard/remuneration/services/exporter.ts
// import { FacultyInfo } from '../types/faculty';
// import { Activity } from '../types/activity';
// import { calculateInsights } from './calculations';

// export function exportWithInsights(faculty: FacultyInfo, activities: Activity[], grandTotal: number, estimatedTime: number) {
//   const insights = calculateInsights(activities, grandTotal, estimatedTime);

//   const rows = [
//     ['A.P. Shah Institute of Technology - Faculty Remuneration Report'],
//     [''],
//     [`Faculty: ${faculty.name}`, `Date: ${faculty.date}`],
//     [`Department: ${faculty.department}`, `Examination: ${faculty.examination}`],
//     [''],
//     ['Sr.No', 'Activity', 'Semester', 'Subject', 'Count', 'Rate', 'Total'],
//     ...activities.filter(a => a.count > 0).map((a, i) => [
//       (i + 1).toString(), a.type, a.sem, a.subject, a.count.toString(), a.rate.toString(), a.total.toString()
//     ]),
//     [''],
//     ['', '', '', '', '', 'Grand Total:', grandTotal.toString()],
//     [''],
//     ['INSIGHTS'],
//     [`Estimated Hours: ${estimatedTime}h`],
//     [`Most Common Activity: ${insights.mostCommonActivity}`],
//     [`Average Rate: ₹${insights.averageRate.toFixed(2)}`],
//     [`Productivity: ₹${insights.productivity.toFixed(2)}/hour`]
//   ];

//   const csvContent = rows.map(r => r.join(',')).join('\n');
//   const blob = new Blob([csvContent], { type: 'text/csv' });
//   const url = URL.createObjectURL(blob);
//   const a = document.createElement('a');
//   a.href = url;
//   a.download = `${faculty.name.replace(/\s+/g, '_')}_remuneration_${faculty.date}.csv`;
//   a.click();
//   URL.revokeObjectURL(url);
// }


// app/dashboard/remuneration/services/exporter.ts
import { FacultyInfo } from '../types/faculty';
import { Activity } from '../types/activity';
import { calculateInsights } from './calculations';

export function exportWithInsights(faculty: FacultyInfo, activities: Activity[], grandTotal: number, estimatedTime: number) {
  const insights = calculateInsights(activities, grandTotal, estimatedTime);

  const rows = [
    ['A.P. Shah Institute of Technology - Faculty Remuneration Report'],
    [''],
    [`Faculty: ${faculty.name}`, `Employee ID: ${faculty.employeeId}`],
    [`Department: ${faculty.department}`, `Date: ${faculty.date}`],
    [`Examination: ${faculty.examination}`, `Scheme: ${faculty.scheme}`],
    [`Branch: ${faculty.branch}`, `Class: ${faculty.class}`],
    [''],
    ['Sr.No', 'Activity', 'Category', 'Difficulty', 'Semester', 'Subject', 'Examination', 'Scheme', 'Class', 'Count', 'Rate', 'Total'],
    ...activities.filter(a => a.count > 0).map((a, i) => [
      (i + 1).toString(), 
      a.type, 
      a.category,
      a.difficulty,
      a.semester, // Changed from a.sem to a.semester
      a.subject, 
      a.examination || faculty.examination, // Use activity-specific or faculty default
      a.scheme || faculty.scheme,
      a.class || faculty.class,
      a.count.toString(), 
      a.rate.toString(), 
      a.total.toString()
    ]),
    [''],
    ['', '', '', '', '', '', '', '', '', 'Grand Total:', grandTotal.toString()],
    [''],
    ['═══════════════════════════════════════════════════════════════'],
    ['📊 EXAMEASE INSIGHTS & ANALYTICS'],
    ['═══════════════════════════════════════════════════════════════'],
    [`⏰ Estimated Working Hours: ${estimatedTime}h`],
    [`🏆 Most Common Activity: ${insights.mostCommonActivity}`],
    [`💰 Average Rate: ₹${insights.averageRate.toFixed(2)}`],
    [`⚡ Productivity Score: ₹${insights.productivity.toFixed(2)}/hour`],
    [`📈 Total Activities Completed: ${activities.filter(a => a.count > 0).length}`],
    [`🎯 Activity Breakdown:`],
    ...Object.entries(
      activities.filter(a => a.count > 0).reduce((acc, a) => {
        acc[a.category] = (acc[a.category] || 0) + 1;
        return acc;
      }, {} as Record<string, number>)
    ).map(([category, count]) => [`   • ${category}: ${count} activities`]),
    [''],
    ['Generated by ExamEase - Faculty Management System'],
    [`Report generated on: ${new Date().toLocaleString()}`]
  ];

  const csvContent = rows.map(r => Array.isArray(r) ? r.join(',') : r).join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `ExamEase_${faculty.name.replace(/\s+/g, '_')}_${faculty.examination.replace(/\s+/g, '_')}_${faculty.date}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}